### ISSUE TITLE
Does gasm only support tinygo WASM modules?

### ISSUE THREAD

**Issue by simar7** [mathetake/gasm#25]
I tried a little experiment to validate this but it didn't work. Below is the experiment:

```Golang
package main

const wasmBytecode = `
	(module
	  (type (func (param i32 i32) (result i32)))
	  (func (type 0)
	    local.get 0
	    local.get 1
	    i32.add)
	  (export "sum" (func 0)))
`

func main() {
	wasm, _ := wasmtime.Wat2Wasm(wasmBytecode) // notice not tinygo
	mod, err := gasm.DecodeModule(bytes.NewBuffer(wasm))
	if err != nil {
		panic(err)
	}
	vm, _ := gasm.NewVM(mod, wasi.New().Modules())
	b.ResetTimer()

	_, _, _ = vm.ExecExportedFunction("sum", uint64(5), uint64(37))
}
```

Which resulted in a panic:
```
panic: runtime error: index out of range [0] with length 0
```

Just wanted to clarify if what I observed is expected.

**Comment by mathetake** [comment]
@simar7 Thanks for this report. This is unexpected and I call this a bug. Looks like we hit this panic here (https://github.com/mathetake/gasm/blob/master/wasm/vm.go#L47) and this is because I had an assumption that every module has data section and we initialize the memory index space by using it:
https://github.com/mathetake/gasm/blob/71556e50c408c57f8f50b419443c927654d4c216/wasm/module.go#L116
https://github.com/mathetake/gasm/blob/71556e50c408c57f8f50b419443c927654d4c216/wasm/module.go#L262

sorry my memory on this project is fuzzy and won't be able to work on a fix anymore (because i don't have cycles for working on gasm... maybe I should archive the repository). But anyway thank you for playing with this and apologies for the bug! Thank you!

**Comment by simar7** [comment]
No worries - thank you for the fast response. It's unfortunate as gasm is and will be an interesting project but I appreciate your hard work.

**Comment by mathetake** [comment]
FYI I slowly started refactoring gasm VM again to pass all the Wasm Specification semantics tests. Stay tuned!

**Comment by mathetake** [comment]
https://github.com/mathetake/gasm/pull/27 this will resolve this! See you there :D
